### ISSUE TITLE
you asked!

### ISSUE THREAD

**Issue by beckycaret** [mrobinson-ws/usercreation-azuread#7]
![image](https://user-images.githubusercontent.com/36257584/123162982-37da1780-d43f-11eb-8775-d3464619f869.png)
Issue for Non-Matching SkuPartNumber 9c7bff7a-3715-4da7-88d3-07f57f8d0fb6 - D365_SALES_PRO_IW 
Issue for Non-Matching SkuPartNumber 6070a4c8-34c6-4937-8dfb-39bbc6397a60 - MEETING_ROOM 
Issue for Non-Matching SkuPartNumber 8c4ce438-32a7-4ac5-91a6-e22ae08d9c8b - RIGHTSMANAGEMENT_ADHOC

**Comment by mrobinson-ws** [comment]
This has been added
